### ISSUE TITLE
Generator creates incorrect stylesheet and js link references for Rails 3.1

### ISSUE THREAD

**Issue by bstar** [RailsApps/rails3-mongoid-devise#1]
Rails 3.1's asset pipeline cannot properly compile css and js due to naming convention changes.

See application.html.haml

Generator creates:
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults

For Rails 3.1 should read:
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"

If this isn't modified, rails will try to find all.css and defaults.js, which of course don't exist.

**Comment by fortuity** [comment]
Thanks for reporting the issue. The application template was updated for Rails 3.1 yesterday. If you generate a new app from the template you should see the corrected code. Let me know if it works for you.

-- Daniel

**Comment by bstar** [comment]
Daniel, thanks for responding to the ticket.  I re-ran the generator and
everything seems to be working fine now.  Appreciate the effort you've put
into all these generators!

**Comment by fortuity** [comment]
Excellent news. Thanks for the appreciation! More good things to come.
