### ISSUE TITLE
Mongoid 2.3.0 requires MongoDB 2.0

### ISSUE THREAD

**Issue by jasonprins** [RailsApps/rails3-mongoid-devise#10]
I cannot confirm this being an issue, but maybe a note is required within the deploy to Heroku section that the MongoHQ and MongoLab Heroku add-ons support up to MongoDB 1.8 at the present time?

**Comment by strcrzy** [comment]
is there some sort of workaround for this?
i'm encountering the same problem :(

what does it require from 2.0 that's not in 1.8?

**Comment by jasonprins** [comment]
MongoHQ and MongoLab both are now supporting MongoDB 2.0.2
