### ISSUE TITLE
Missing newline in Gemfile at line 48

### ISSUE THREAD

**Issue by ShonM** [RailsApps/rails3-mongoid-devise#12]
After running:

```
rails new projectname -m https://github.com/RailsApps/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb -T -O
```

The code reads: gem "guard", ">= 0.6.2", :group => :developmentcase HOST_OS

Should have a newline between "development" and "case" I think?

Rails 3.1.3

**Comment by DanielKehoe** [comment]
This issue has been fixed in the newest application template. Thank you for pointing it out.
