### ISSUE TITLE
database.yml error when creating app from template

### ISSUE THREAD

**Issue by jonathanhoskin** [RailsApps/rails3-mongoid-devise#13]
Mac OS 10.7
Rails: 3.2
Ruby 1.9.3-p0 (rbenv)

rails new myapp -m https://github.com/RailsApps/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb

Answering YES to everything except HAML, and option # 3 for Twitter Bootstrap.

It looks like problem is that the Mongo recipe deletes database.yml, but then the Devise recipe is looking for it.

https://gist.github.com/1723070

**Comment by DanielKehoe** [comment]
Could you try running this with the -T -O flags to skip Test::Unit files and Active Record files, please. I think it will work. The layout for the README file seems to hide the  -T -O flags in the example command.

Let me know if this resolves the issue and reopen it if necessary.

-- Daniel
