### ISSUE TITLE
ExecJS::RuntimeUnavailable when using the template + solution

### ISSUE THREAD

**Issue by cornuwel** [RailsApps/rails3-mongoid-devise#16]
Hi, I just started an app with the provided generator and it fails with this error:

generate    rspec:install
/home/julien/.rvm/gems/ruby-1.9.3-p125/gems/execjs-1.3.0/lib/execjs/runtimes.rb:50:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)

All you have to do is add these to the Gemfile:
gem 'execjs'
gem 'therubyracer'

Regards

**Comment by DanielKehoe** [comment]
For development on Linux Ubuntu, it is best to install the Node.js server-side JavaScript environment. See the article "Installing Rails 3.2":
http://railsapps.github.com/installing-rails.html
