### ISSUE TITLE
Sprockets version

### ISSUE THREAD

**Issue by l4u** [RailsApps/rails3-mongoid-devise#18]
Your bundle is updated! Use `bundle show [gemname]` to see where a bundled gem is installed.
      wizard  Running 'after bundler' callbacks.
The template [https://github.com/RailsApps/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb] could not be loaded. Error: You have already activated sprockets 2.1.2, but your Gemfile requires sprockets 2.1.3. Using bundle exec may solve this.

**Comment by DanielKehoe** [comment]
This error usually goes away if you try to generate the application a second time. Are you still getting the error when you retry? Please re-open the issue if you do.
