### ISSUE TITLE
Generate rspec failing with Rails 3.1.0.rc4

### ISSUE THREAD

**Issue by naleksi** [RailsApps/rails3-mongoid-devise#2]
Hello!

Thanks for awesome tutorial! I tried to follow the manual steps for 

   https://github.com/RailsApps/rails3-mongoid-devise/wiki/Tutorial

but failed at "Adding RSpec for Unit Testing" / "Generate rspec" when running:

  $ rails generate rspec:install

with 

/Users/foo/.rvm/gems/ruby-1.9.2-p180@rails-devise-mongoid-app-test/gems/actionpack-3.1.0.rc4/lib/action_view/railtie.rb:34:in `block (3 levels) in <class:Railtie>': undefined method`debug_rjs=' for ActionView::Base:Class (NoMethodError)
    from /Users/foo/.rvm/gems/ruby-1.9.2-p180@rails-devise-mongoid-app-test/gems/actionpack-3.1.0.rc4/lib/action_view/railtie.rb:33:in `each'
    from /Users/foo/.rvm/gems/ruby-1.9.2-p180@rails-devise-mongoid-app-test/gems/actionpack-3.1.0.rc4/lib/action_view/railtie.rb:33:in`block (2 levels) in class:Railtie'

The cause seems to be indicated by this commit which removes debug_rjs: https://github.com/rails/rails/commit/d8f23ca627df85b33fe8db87db5483c10b62bfe6

And here's the trivial change, once you found it, comment the debug_rjs away from config/environments/development.rb:

diff --git a/config/environments/development.rb b/config/environments/development.rb
index b0b4221..ae986ab 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -11,7 +11,7 @@ Kupla::Application.configure do

   # Show full error reports and disable caching
   config.consider_all_requests_local       = true
-  config.action_view.debug_rjs             = true
-  #config.action_view.debug_rjs             = true
  config.action_controller.perform_caching = false
  # Don't care if the mailer can't send

I guess this needs to be fixed in Rails.

Thought to let you know anyway.

**Comment by fortuity** [comment]
Hmm. If you generated a new Rails app using Rails 3.1.0.rc4, your `development.rb` file should not contain any references to `debug_rjs`. I'm not sure where you got that `development.rb` file. I've checked and the tutorial does not contain any references to `debug_rjs`. The example source code was updated 1 June 2011 to conform to Rails 3.1 so there should be no reference there either. I'll close this issue for now but please reopen it if you continue to see a problem.
