### ISSUE TITLE
Mongoid.master

### ISSUE THREAD

**Issue by jackperry** [RailsApps/rails3-mongoid-devise#20]
I was going through the tutorial and was getting thrown an error on Mongoid.master. It seems it's not supported in the latest Mongoid anymore. I'm not sure if Mongoid.purge is considered the best option here, but I here's the updated code I got working:

``` ruby
puts 'EMPTY THE MONGODB DATABASE'
Mongoid.purge!
puts 'SETTING UP DEFAULT USER LOGIN'
user = User.create! :name => 'First User', :email => 'user@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user.name
```

**Comment by DanielKehoe** [comment]
I'm using Mongoid v2.4.11 and can't reproduce the problem. Which version of Mongoid are you using?

**Comment by jackperry** [comment]
3.0.0rc. Perhaps I'm just a bit too early with adopting it.

**Comment by DanielKehoe** [comment]
I'm planning to rewrite the tutorials when 3.0 final is released. I intend to remove

```
puts 'EMPTY THE MONGODB DATABASE'
Mongoid.purge!
```

as it is better to use "rake db:reseed" I believe.

Thanks for bringing this to my attention.
