### ISSUE TITLE
Cant setup new user db:seed

### ISSUE THREAD

**Issue by climbingblake** [RailsApps/rails3-mongoid-devise#22]
having worked several times before, but the most current version of the template is puking on me when attemtping to run seed:db from the generator template....  
Im running in a new gemset on my localhost RVM 1.9.2 , resulting in the following error.... I cant seem to track down the reason.
Anyone else having this issue?

$ bundle exec rake db:seed
SETTING UP DEFAULT USER LOGIN
rake aborted!
undefined method `[]' for nil:NilClass

Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by DanielKehoe** [comment]
The newest version of the template will install Mongoid 3.0 and Mongoid 3.0 only supports Ruby 1.9.3. That may be the reason you're seeing the error with Ruby 1.9.2.

**Comment by climbingblake** [comment]
Thanks Daniel, this may be the issue.. 
Now im getting crazy errors trying to get 1.9.3 working correctly on my osx, but Im betting this is the problem.

**Comment by DanielKehoe** [comment]
For trouble running 1.9.3, see http://railsapps.github.com/installing-rails.html. You may need to reinstall rvm.

**Comment by climbingblake** [comment]
Thanks again Daniel, i will have to revisit this tonight... im getting a error after installing and trying to run bundle...

Segmentation fault ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin11.4.0]
