### ISSUE TITLE
'bundle exec rake db:migrate from "."' fails

### ISSUE THREAD

**Issue by tomoyuki28jp** [RailsApps/rails3-mongoid-devise#24]
I run the following command:
rails new myapp -m https://github.com/RailsApps/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb -T -O

Then I got following errors:

```
     run    bundle exec rake db:migrate from "."
```

rake aborted!

Problem:
  Invalid index specification on Role: name, {:unique=>true}
Summary:
  Indexes in Mongoid are defined as a hash of field name and direction/2d pairs, with a hash for any additional options.
Resolution:
  Ensure that the index conforms to the correct syntax and has the correct options.

 Valid options are:
   background: true|false
   drop_dups: true|false
   name: 'index_name'
   sparse: true|false
   unique: true|false

 Valid types are: 1, -1, '2d'

 Example:
   class Band
     include Mongoid::Document
     index({ name: 1, label: -1 }, { sparse: true })
     index({ location: '2d' }, { background: true })
   end

Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
    generate    devise_invitable user
      insert  app/models/user.rb
      invoke  mongoid
  seed_database  creating indexes and seeding the database
         run    rake db:mongoid:create_indexes from "."
rake aborted!

Problem:
  Invalid index specification on Role: name, {:unique=>true}
Summary:
  Indexes in Mongoid are defined as a hash of field name and direction/2d pairs, with a hash for any additional options.
Resolution:
  Ensure that the index conforms to the correct syntax and has the correct options.

 Valid options are:
   background: true|false
   drop_dups: true|false
   name: 'index_name'
   sparse: true|false
   unique: true|false

 Valid types are: 1, -1, '2d'

 Example:
   class Band
     include Mongoid::Document
     index({ name: 1, label: -1 }, { sparse: true })
     index({ location: '2d' }, { background: true })
   end

Tasks: TOP => db:mongoid:create_indexes => environment
(See full trace by running task with --trace)
         run    bundle exec rake db:seed from "."
rake aborted!

Problem:
  Invalid index specification on Role: name, {:unique=>true}
Summary:
  Indexes in Mongoid are defined as a hash of field name and direction/2d pairs, with a hash for any additional options.
Resolution:
  Ensure that the index conforms to the correct syntax and has the correct options.

 Valid options are:
   background: true|false
   drop_dups: true|false
   name: 'index_name'
   sparse: true|false
   unique: true|false

 Valid types are: 1, -1, '2d'

 Example:
   class Band
     include Mongoid::Document
     index({ name: 1, label: -1 }, { sparse: true })
     index({ location: '2d' }, { background: true })
   end

Tasks: TOP => db:seed => environment
(See full trace by running task with --trace)

**Comment by tomoyuki28jp** [comment]
This change fixes the issue:

app/models/role.rb

```
-  index :name, unique: true
-  index(
-    [
-      [:name, Mongo::ASCENDING],
-      [:resource_type, Mongo::ASCENDING],
-      [:resource_id, Mongo::ASCENDING]
-    ],
-    unique: true
-  )
+  index({name:1}, {unique:true})
+  index({name:1, resource_type:1, resource_id:1}, {unique:true})
```

**Comment by DanielKehoe** [comment]
@tomoyuki28jp Thank you for identifying this issue. The application template uses a generator from Rolify `generate 'rolify:role Role User mongoid'` to modify the User model. I believe this issue was reported as https://github.com/EppO/rolify/pull/89 and will be fixed in the next release of the Rolify gem.

**Comment by tomoyuki28jp** [comment]
@DanielKehoe I see, thanks for your reply and great work! :)
