### ISSUE TITLE
Should include Application.example.yml file

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#27]
Since this is for beginners, then following good practice, two identical files:

config/application.yml
config/application.example.yml

should be created and (both) discussed in the [Configuration File](https://github.com/RailsApps/rails3-mongoid-devise#configuration-file) section of the README.

Obviously, the example file (in source control) is visible to developers when they join a project; the other should be ignored by .gitignore.

Both should contain the text:

``` ruby
# Each developer, when first cloning the repository, should
#   copy this file, removing '.example' from its name.
# This file (unless it's -.example.yml) should be listed in .gitignore
#   to keep your settings secret!
```

**Comment by DanielKehoe** [comment]
Hmm, I wonder if you saw the latest version of the README and the app. Updated yesterday. I think it's all you've asked for, though I don't mention the `config/application.example.yml` file. Further advice appreciated if you have more feedback.

**Comment by MarkDBlackwell** [comment]
Yes, I generated it today.

However, this issue is for _later_ developers who join the project, after it is generated.

Those new developers won't see config/application.yml (which is good, BTW) when they clone the project, because it's in .gitignore.

That's why this issue suggests _also_ supplying, fairly easily, an identical config/application.example.yml, containing the instructions for that new developer (as shown in the issue).

Using two files in this way is a common practice, and here we can help beginners protect their confidential information.

**Comment by DanielKehoe** [comment]
The file is in the repo:
https://github.com/RailsApps/rails3-mongoid-devise/blob/master/config/application.example.yml
Do you see it?

Good enough?

**Comment by MarkDBlackwell** [comment]
Ah...I see it now (what was I thinking?) You are so right—I see both files there. And, that's good work you did! :)

I think I had a flag up, about the copying instructions. Sorry for my confusion!

If new arrivals on a project are already MongoDB developers, copying the two files is obvious.

With powerful app generators for newbies, explicitly include these copying instructions still might seem helpful, IMHO.

**Comment by DanielKehoe** [comment]
I gave it some thought and I think it will be clear. Later developers will read the README and see the explanation about the config/application.yml file and find the config/application.example.yml. I think that's enough.
