### ISSUE TITLE
Unneeded Gmail environment variables shouldn't be generated in application.yml

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#28]
The [Configure Email](https://github.com/RailsApps/rails3-mongoid-devise#configure-email) section of README informs us this example Rails app doesn't send out email.

Presently, GMAIL_USERNAME and GMAIL_PASSWORD are generated in config/application.yml. Perhaps they are useful only for sending outgoing email.

Therefore, perhaps they should be removed, so having two usernames and passwords doesn't puzzle beginners.

**Comment by DanielKehoe** [comment]
I'll give it some thought. I left them in as examples. But you're right, it could be confusing.
