### ISSUE TITLE
Use Figaro to access environment variables

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#29]
Regarding accessing environment variables from db/seeds.rb, as well as in the section, [Set Up a Database Seed File](https://github.com/RailsApps/rails3-mongoid-devise#set-up-a-database-seed-file), of the README:

Since the Rails composer is using Figaro, why not follow the style of code, suggested by the Figaro gem's [README](https://github.com/laserlemon/figaro#give-me-an-example), to access the environment variables? E.g.:

user = User.create! name: Figaro.env.admin_name

**Comment by DanielKehoe** [comment]
Using ENV variables makes it possible to eliminate Figaro if a developer prefers to use Unix environment variables. Many developers prefer to use Unix environment variables.
