### ISSUE TITLE
Factory Girl 2.0.0.rc3 is broken, need to use FG 2.0.0.rc1 until they fix

### ISSUE THREAD

**Issue by ethank** [RailsApps/rails3-mongoid-devise#3]
This seems to be a known issue. See here: https://github.com/thoughtbot/factory_girl/issues/156

After using the generator, put this in the gem file:

gem "factory_girl", :git => 'git://github.com/thoughtbot/factory_girl.git', :tag=>'v2.0.0.rc1'

**Comment by fortuity** [comment]
The issue can be resolved by using FactoryGirl 2.0.0.rc4. I've updated the Rails Apps Composer, the application template, and the example source code accordingly.
