### ISSUE TITLE
README-suggested Rake task fails to empty and reseed the database

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#30]
The [Set the Database](https://github.com/RailsApps/rails3-mongoid-devise#set-the-database) section of the README says:

'Use rake db:reset if you want to empty and reseed the database'

However, `rake db:reset` doesn't exist, since we're using the mongoid gem (and Rake gives an error).

Per `rake --tasks`, this should be `rake db:reseed` (or so it seems).

**Comment by DanielKehoe** [comment]
Good catch. Thanks for reading the docs with an eagel eye.

I've updated the README to say "Use @rake db:reseed@ if you want to empty and reseed the database. Or you can use @rake db:drop@ and @rake db:setup@. The equivalent task for Rails with ActiveRecord is @rake db:reset@ which will be available in Mongoid 4.0."
