### ISSUE TITLE
Default password specified in README fails to work

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#31]
The [Test the App](https://github.com/RailsApps/rails3-mongoid-devise#test-the-app) section of the README says:

To sign in as the default user, (unless you’ve changed it) ...

and gives a password.

However, this password differs from the default password (for the Admin user) in [config/application.yml](https://github.com/RailsApps/rails3-mongoid-devise/blob/master/config/application.yml).

**Comment by DanielKehoe** [comment]
Thanks, fixed it.
