### ISSUE TITLE
README should caveat `rake cucumber` won't run @wip cukes

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#32]
A certain subtlety exists regarding `rake cucumber` and Cucumber's standard Work In Progress cukes (those tagged with `@wip`).

`rake cucumber` has the same effect as `rake cucumber:ok`. It does not have the same effect as `rake cucumber:all`.

In light of this, the following statement in the [Testing](https://github.com/RailsApps/rails3-mongoid-devise/#testing) section of the README:

'Run rake cucumber (or more simply, cucumber) to run all Cucumber scenarios'

perhaps (to avoid misleading newbies to Cucumber) should be changed to:

'... all Cucumber scenarios (that are not tagged with @wip, for work in progress. And if you don't know what that means, then you don't need to worry about it).'

**Comment by DanielKehoe** [comment]
Thanks for pointing out that nuance but I think I'll skip it. I have to draw the line sometimes at including detail and this subtlety doesn't become an issue until someone has studied Cucumber enough to know how to use @wip.

**Comment by MarkDBlackwell** [comment]
On nuances and detail, truly one does need to draw the line somewhere, to avoid confusing beginners. :)

It is because I know almost nothing about what `@wip` cukes might be, that I want to run `rake cucumber:all`.

I am merely a one-day Cucumber newby, not an expert, and I looked at `rake --tasks` in response to this README.

My goal was to build my 'Cucumber' confidence about running 'all cukes' —whether this (always) will run all of my (own) cukes. Or, whether something unknown could perhaps blindside me one day, if I form the habit of running 'all cukes'.

Since you think it's perfectly safe, then I agree it's better not to mention the `@wip` cukes.

**Comment by DanielKehoe** [comment]
@MarkDBlackwell please email me at daniel@danielkehoe.com.

**Comment by MarkDBlackwell** [comment]
On further reflection, if the word, 'all' were removed from the sentence so it said:

'Run rake cucumber (or more simply, cucumber) to run your Cucumber scenarios'

that would solve the problem.

**Comment by DanielKehoe** [comment]
Good! Done. Thanks!

Please email me so I can send you a thank you.
