### ISSUE TITLE
'Login' and 'Logout' used inconsistently along with 'Sign in' and 'Sign out'

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#33]
In the navigation header, the user sees 'Login' and 'Logout' (in _navigation.html.haml); user_steps.rb contains 'Login' and 'Logout'.

On the other hand, Devise seems to prefer something else: once a user clicks Login, bold letters say 'Sign in' (in app/views/devise/shared/_links.html.haml).

Following Devise, sign_out.feature contains 'Feature: Sign out', sign_in.feature contains 'Feature: Sign in', and support/paths.rb contains 'sign in'. Some step definitions include 'logged in' and 'not logged in'.

I know it all works, yet newby users will be customizing the cukes for their apps.

Perhaps usefully, 'Log' and 'Sign' (in the features) have slightly different meanings. Yet, to make things easiest, and for elegant simplicity, isn't it better to use 'Sign in' and 'Sign out' only, always and everywhere?

Probably otherwise, people will wonder, and spend time figuring out, what the difference is. If useful, the difference could be documented for newby users.

**Comment by schadenfred** [comment]
That's an interesting question.  I remember trying to figure out the difference between logging in and signing in, to no avail.  I'd say log in sounds better to me, but you have a good point about customizing the default devise sign up/sign in behavior may confuse people.  that's my .02.

**Comment by DanielKehoe** [comment]
AFAIK, 'Login' and 'Sign in' mean the same thing. I think 'Login' is used more often than 'Sign in'. If you can point me to a UX or IxD authority that can make a case for either, I'll make a change. Otherwise, the web is inconsistent and I see no need to make a change here.
