### ISSUE TITLE
Unclear instruction for code modification to create a default user

### ISSUE THREAD

**Issue by KyleCrop** [RailsApps/rails3-mongoid-devise#36]
Under the heading "Create a Default User" the instructions read: 

"Modify the file app/controllers/home_controller.rb and add:"

def index
  @users = User.all
end
# 

Well, in that specified file, there already exists the lines

"def index
end"

I first appended the instructed 3 lines of code to the end of that file, which led to an error. I was able to troubleshoot that error (which seemed to be in the next file referenced by the instructions) and found that the issue was that I was suppose to just add that second line  "  @users = User.all" in between the 2 lines already given in my file. I'm brand new to this so simply following the instructions I did not know (if) this was meant. Perhaps say to write that one line of code between the other 2 rather than "add the following code." 

Other than that, all else has been amazing! Thanks for a very helpful tutorial!

**Comment by DanielKehoe** [comment]
I've clarified the tutorial as you suggested. Thank you!
