### ISSUE TITLE
README doesn't need to mention `db:test:prepare`

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#37]
The [README](https://github.com/RailsApps/rails3-mongoid-devise/blob/master/README.textile#set-the-database) recommends users set up their test environment with `db:test:prepare`.

However, automatically now during testing, Rails itself does `db:test:prepare`, as revealed by `bundle exec rake --trace`. So, this step in the README doesn't add anything.

This is similar to an [issue](https://github.com/RailsApps/rails3-bootstrap-devise-cancan/issues/37) in another Rails Example App.

**Comment by DanielKehoe** [comment]
I am not aware that `rake db:test:prepare` is no longer necessary. The [RailsGuide: A Guide to Testing Rails Applications](http://guides.rubyonrails.org/testing.html) recommends it. And the newest version of [Michael Hartl's book](http://ruby.railstutorial.org/book/ruby-on-rails-tutorial?version=4.0) recommends it. Can you provide a link to an authority that states it is no longer necessary?

**Comment by MarkDBlackwell** [comment]
Users need to do this before invoking Cucumber or RSpec without Rake, so closing.

**Comment by MarkDBlackwell** [comment]
In various Rails Apps repositories, as you may be aware by now—in response to the good point you made here—I have closed all the issues (I think) regarding this.

Though the choice of not using Rake (I judge) complicates the users' process of setting up (an app) for each test run, the argument of increased speed (without Rake) is a powerful one.

Furthermore, Rake relays very few (if any, as far as I know) of the arguments that can drive RSpec and Cucumber. Therefore currently as I see it, Rake is unsuitable for running merely a single spec or feature. This limitation cripples Rake's testing functionality—I wish Rake were improved in that way! Please let me know if I am mistaken in this perception.

EDIT: Rake can pass arguments to Cucumber and RSpec per its [RDoc](http://rake.rubyforge.org/doc/rakefile_rdoc.html) section _Tasks with Arguments,_ and various websearches reveal how to run a single spec or feature through Rake. However, if a test passes without Rake, running it with Rake still would be slower.
