### ISSUE TITLE
Devise requires a method for destroy_user_session_path

### ISSUE THREAD

**Issue by ethank** [RailsApps/rails3-mongoid-devise#4]
In _login_items_.html.haml

``` haml
    = link_to('Logout', destroy_user_session_path,  :method=>'delete')


You have to include the method in order for it to route properly. Appears to be a devise bug.
```

**Comment by randomm** [comment]
I also ran into this issue today, thanks for posting...!

**Comment by ethank** [comment]
Interestingly enough when I hand build this (not using any of the scripts in RailsApps), I did not run into this problem.

**Comment by azzab** [comment]
this fix worked for me adding :method=>'delete'

**Comment by fortuity** [comment]
By default, Devise uses an http DELETE request for sign out requests (`destroy_user_session_path`). Rails uses Javascript to implement http DELETE requests. Prior to Devise 1.4.1 (27 June 2011), Devise used an http GET request for sign out requests. Jose Valim explained the change: "GET requests should not change the state of the server. When sign out is a GET request, CSRF can be used to sign you out automatically and things that preload links can eventually sign you out by mistake as well."

However, Cucumber wants to test GET requests not DELETE requests. If you intend to use Cucumber with Devise, you must change the Devise default from DELETE to GET in `/config/initializers/devise.rb` for the Rails test environment. You may see a suggestion elsewhere to tweak the routes.rb file to make the fix. It isn't necessary if you change the /config/initializers/devise.rb file.

``` ruby
# The default HTTP method used to sign out a resource. Default is :delete.
config.sign_out_via = Rails.env.test? ? :get : :delete
```

This should resolve the issue in either Rails 3.0.9 or 3.1.0. Please reopen the issue if you run into problems.

I've updated the application template and the Rails Apps Composer gem to detect the collision between Devise and Cucumber and the template will make the change to the Devise initializer when Cucumber is included. The example source code now implements the change. I have updated the tutorial as well.

**Comment by azzab** [comment]
nope didn't work for me 
BSON::InvalidObjectId in UsersController#show

illegal ObjectId format

using 
  # The default HTTP method used to sign out a resource. Default is :delete.
  config.sign_out_via = :get

**Comment by fortuity** [comment]
Let's see your Gemfile, please.

If possible, please clone the latest version of the example code and run a comparison to identify the differences. On a Mac, you can use FileMerge.app, DiffMerge.app, or Ian Baird's Changes.app (my favorite).

**Comment by azzab** [comment]
ok I will try the diffmerge 

thats my Gemfile

source 'http://rubygems.org'
gem 'rails', '3.1.0.rc4'
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'
gem 'jquery-rails'
gem "haml", ">= 3.1.2"
gem "haml-rails", ">= 0.3.4", :group => :development
gem "rspec-rails", ">= 2.6.1", :group => [:development, :test]
gem "database_cleaner", ">= 0.6.7", :group => :test
gem "mongoid-rspec", ">= 1.4.4", :group => :test
gem "factory_girl_rails", ">= 1.1.beta1", :group => :test
gem "cucumber-rails", ">= 1.0.0", :group => :test
gem "capybara", ">= 1.0.0", :group => :test
gem "launchy", ">= 0.4.0", :group => :test
gem "bson_ext", ">= 1.3.1"
gem "mongoid", ">= 2.0.2"
gem "devise", ">= 1.3.4"
gem "rails-footnotes", ">= 3.7", :group => :development
group :development do
  gem 'heroku_san'
end

gem 'execjs'

gem 'therubyracer'

**Comment by fortuity** [comment]
Try updating Devise:

`gem "devise", ">= 1.4.2"`

and while you're at it:

`gem "factory_girl_rails", ">= 1.1.rc1", :group => :test`
`gem "cucumber-rails", ">= 1.0.2", :group => :test`

And `bundle update`.

**Comment by schwatvogel** [comment]
hmm,
same problem here
using devise (1.4.4)
already tried using the suggestion of setting the :delete method manually:
`<%= link_to "Log out", destroy_user_session_path, :method => :delete %>`
but it doesn't do the trick
al still get a get request with 
`{"id"=>"sign_out"}`

any hints?

**Comment by jaredfolkins** [comment]
I also has this issue, cailinanne's fix worked for me.

https://github.com/RailsApps/rails3-devise-rspec-cucumber/issues/3

The easiest way to "get this working" is to force the routes to match the application. You can do this by modifying the routes file.

Remove:

``` ruby
devise_for :users
```

Add:

``` ruby
devise_for :users do
  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
end
```

**Comment by schwatvogel** [comment]
weeee,
thanks a lot, that did the trick

**Comment by DanielKehoe** [comment]
Per José Valim's suggestion here:

https://github.com/plataformatec/devise/issues/1195

I've changed the example app and application template so the 'Logout' link will include `:method=>'delete'`:

`<%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>`

Since we are using Cucumber, the /config/initializers/devise.rb file will be set like this:

<pre>
# The default HTTP method used to sign out a resource. Default is :delete.
config.sign_out_via = Rails.env.test? ? :get : :delete
</pre>


The HTTP DELETE method will be used to sign out a user in development and production environments and the HTTP GET method will be used in the test environment when Cucumber runs.

I believe it's better to change the 'Logout' link in the app than to change the routes file.

As far as I am able to determine, this represents current best practice.

Please reopen the issue if this is unsatisfactory.

-- Daniel
