### ISSUE TITLE
Can't get cucumber tests to pass

### ISSUE THREAD

**Issue by ethank** [RailsApps/rails3-mongoid-devise#5]
I'm unable to get about 5 steps to pass in cucumber.

Failing Scenarios:
cucumber features/users/sign_in.feature:24 # Scenario: User signs in successfully with email
cucumber features/users/sign_out.feature:6 # Scenario: User signs out
cucumber features/users/sign_up.feature:6 # Scenario: User signs up with valid data
cucumber features/users/sign_up.feature:15 # Scenario: User signs up with invalid email
cucumber features/users/user_edit.feature:6 # Scenario: I sign in and edit my account

For instance:

  Scenario: I sign in and edit my account                                             # features/users/user_edit.feature:6
    Given I am a user named "foo" with an email "user@test.com" and password "please" # features/step_definitions/user_steps.rb:5
    When I sign in as "user@test.com/please"                                          # features/step_definitions/user_steps.rb:43
      illegal ObjectId format (BSON::InvalidObjectId)
      ./app/controllers/users_controller.rb:6:in `show'
      (eval):2:in`click_button'
      ./features/step_definitions/web_steps.rb:53:in `/^(?:|I )press "([^"]*)"$/'
      features/users/user_edit.feature:8:in`When I sign in as "user@test.com/please"'
    Then I should be signed in

**Comment by azzab** [comment]
I have the same issue in rails 3.1.rc4 

s.rb:5
    When I sign in as "user@test.com/please"                                          # features/step_definitions/user_steps.rb:43
      illegal ObjectId format (BSON::InvalidObjectId)
      ./app/controllers/users_controller.rb:5:in `show'
      (eval):2:in`click_button'
      ./features/step_definitions/web_steps.rb:53:in `/^(?:|I )press "([^"]*)"$/'
      features/user_edit.feature:8:in`When I sign in as "user@test.com/please"'

**Comment by dodops** [comment]
the same issue with me, I am using rails version 3.1.3, and cucumber 1.0.6

**Comment by saserbest** [comment]
Couldn't able to deploy to heroku:

`/app/vendor/bundle/ruby/1.9.1/gems/mongo-1.5.2/lib/mongo/connection.rb:413:in 'connect': Failed to connect to a master node at localhost:27017 (Mongo::ConnectionFailure)`

**Comment by dhf0820** [comment]
Turns out it will pass if you specify the correct configuration.  No cancan/rolify, and use HAML. The tests do not seem to be set up for other configurations plus the app generated does not work if you use invitable.

**Comment by DanielKehoe** [comment]
Cucumber tests are now working.
