### ISSUE TITLE
app_name undefined in tutorial

### ISSUE THREAD

**Issue by gsonbuchner** [RailsApps/rails3-mongoid-devise#6]
Thank you for the amazing tutorial.  I have never encountered a better walkthrough.  I ran into one small error.

I followed the link to change the application layout to:

http://railsapps.github.com/rails-default-application-layout.html

I then copied the erb code for Rails 3.1, that included this snippet:

<title><%= app_name %></title>

When I ran the server I received an error:

undefined local variable or method `app_name'

I only mentioned it because it was the only error, I received.

**Comment by fortuity** [comment]
Thanks for the praise, I appreciate it.

Thanks for catching this. It's an artifact of copying the code from the Rails Apps Composer recipe.

I've updated the page to correct the error.

Best luck with your continued coding!

-- Daniel
