### ISSUE TITLE
BSON::InvalidObjectId in UsersController#show accessing users/1 after login

### ISSUE THREAD

**Issue by o-bo** [RailsApps/rails3-mongoid-devise#8]
Step to reproduce : 
    - Create a new empty project with the rails3-mongoid-devise template.
    - After starting the server, Iogin into the app with user@test.com/please.

The page show the following error : 
    BSON::InvalidObjectId in UsersController#show 
    illegal ObjectId format
    app/controllers/users_controller.rb:5:in `show'
    Request
    Parameters:
    {"id"=>"1"}

Here is my Gemfile : 

source 'http://rubygems.org'
gem 'rails', '3.0.9'
gem "haml", "3.1.2"
gem "haml-rails", "0.3.4", :group => :development
gem "rspec-rails", "2.6.1", :group => [:development, :test]
gem "database_cleaner", "0.6.7", :group => :test
gem "mongoid-rspec", "1.4.2", :group => :test
gem "factory_girl_rails", ">= 1.1.rc1", :group => :test
gem "cucumber-rails", ">= 1.0.2", :group => :test
gem "capybara", "1.0.0", :group => :test
gem "launchy", "0.4.0", :group => :test
gem "mongoid", "2.0.2"
gem "devise", ">= 1.4.2"
gem "bson_ext", ">= 1.3.1"

**Comment by o-bo** [comment]
Ok this is not an issue but a misunderstanding of mongodb from me.
Ids are not like '1', '2',... but like '4e5a2858bd0286104c000001'.
If I access localhost:3000/, after login, I have the list of users, and clicking on the first works fine and I can see the good id in the url.
Sorry for this issue.

**Comment by DanielKehoe** [comment]
No problem, thanks for opening the issue and resolving it as other people may have the same misunderstanding.

-- Daniel
